### ISSUE TITLE
LensHaloBaseNSIE

### ISSUE THREAD

**Issue by rbmetcalf** [glenco/SLsimLib#132]
Does this class ever need to be constructed by itself?
If not we should block it.
Jen-Wei found that when she used it in this way the 
kappa was 10x too small. @FabienNugier what do 
you think?

**Comment by FabienNugier** [comment]
Hi, sorry for the very late reply.
LensHaloBaseNSIE is supposed to be a parent class I think.
On my side I use LensHaloFit’s constructor which uses it, but never LensHaloBaseNSIE’s constructor.
So you think there is a mistake in force() of LensHaloBaseNSIE ?

Best regards,
Fabien

**Comment by rbmetcalf** [comment]
In pull request #138  `LensHaloBaseNSIE` is made into an abstract class so that only classes derived from it can be instantiated.
